import math as m
def sin(a):
  return m.sin(a)
def cos(a):
  return m.cos(a)
def tan(a):
  return m.tan(a)
def cot(a):
  return 1/m.tan(a)
def cosec(a):
  return 1/m.sin(a)
def sec(a):
  return 1/m.cos(a)
def tan_inv(a):
  return m.atan(a)
def sin_inv(a):
  return m.asin(a)
def cos_inv(a):
  return m.acos(a)
def cot_inv(a):
  return 1/m.atan(a)
def sec_inv(a):
  return 1/m.acos(a)
def cosec_inv(a):
  return 1/m.asin(a)
